/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  text,
  jsonb,
  boolean,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum__locales = pgEnum("enum__locales", ["ru", "en"]);
export const enum_users_role = pgEnum("enum_users_role", ["admin", "editor"]);
export const enum_cases_social_links_platform = pgEnum(
  "enum_cases_social_links_platform",
  ["instagram", "tiktok", "youtube", "vk"],
);
export const enum_cases_niche = pgEnum("enum_cases_niche", [
  "ecommerce",
  "edu",
  "expert",
  "horeca",
  "beauty",
  "travel",
  "realestate",
  "digital",
  "other",
]);
export const enum_cases_currency = pgEnum("enum_cases_currency", [
  "RUB",
  "USD",
  "EUR",
]);
export const enum_blog_posts_category = pgEnum("enum_blog_posts_category", [
  "cases",
  "analysis",
  "process",
  "myths",
  "news",
]);
export const enum_pricing_currency = pgEnum("enum_pricing_currency", [
  "RUB",
  "USD",
]);
export const enum_faq_category = pgEnum("enum_faq_category", [
  "general",
  "services",
  "pricing",
  "process",
]);
export const enum_footer_social_platform = pgEnum(
  "enum_footer_social_platform",
  ["telegram", "instagram", "youtube", "tiktok", "whatsapp"],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    role: enum_users_role("role").notNull().default("editor"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    caption: varchar("caption"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_card_url: varchar("sizes_card_url"),
    sizes_card_width: numeric("sizes_card_width", { mode: "number" }),
    sizes_card_height: numeric("sizes_card_height", { mode: "number" }),
    sizes_card_mimeType: varchar("sizes_card_mime_type"),
    sizes_card_filesize: numeric("sizes_card_filesize", { mode: "number" }),
    sizes_card_filename: varchar("sizes_card_filename"),
    sizes_hero_url: varchar("sizes_hero_url"),
    sizes_hero_width: numeric("sizes_hero_width", { mode: "number" }),
    sizes_hero_height: numeric("sizes_hero_height", { mode: "number" }),
    sizes_hero_mimeType: varchar("sizes_hero_mime_type"),
    sizes_hero_filesize: numeric("sizes_hero_filesize", { mode: "number" }),
    sizes_hero_filename: varchar("sizes_hero_filename"),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_card_sizes_card_filename_idx").on(
      columns.sizes_card_filename,
    ),
    index("media_sizes_hero_sizes_hero_filename_idx").on(
      columns.sizes_hero_filename,
    ),
  ],
);

export const pages_blocks_content = pgTable(
  "pages_blocks_content",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_content_order_idx").on(columns._order),
    index("pages_blocks_content_parent_id_idx").on(columns._parentID),
    index("pages_blocks_content_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_content_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_content_locales = pgTable(
  "pages_blocks_content_locales",
  {
    content: jsonb("content"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pages_blocks_content_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_content.id],
      name: "pages_blocks_content_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_cta = pgTable(
  "pages_blocks_cta",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    buttonLink: varchar("button_link"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_cta_order_idx").on(columns._order),
    index("pages_blocks_cta_parent_id_idx").on(columns._parentID),
    index("pages_blocks_cta_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_cta_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_cta_locales = pgTable(
  "pages_blocks_cta_locales",
  {
    headline: varchar("headline"),
    text: varchar("text"),
    buttonText: varchar("button_text"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pages_blocks_cta_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_cta.id],
      name: "pages_blocks_cta_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_features_features = pgTable(
  "pages_blocks_features_features",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    icon: varchar("icon"),
  },
  (columns) => [
    index("pages_blocks_features_features_order_idx").on(columns._order),
    index("pages_blocks_features_features_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_features.id],
      name: "pages_blocks_features_features_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_features_features_locales = pgTable(
  "pages_blocks_features_features_locales",
  {
    title: varchar("title"),
    description: varchar("description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "pages_blocks_features_features_locales_locale_parent_id_uniq",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_features_features.id],
      name: "pages_blocks_features_features_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_features = pgTable(
  "pages_blocks_features",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_features_order_idx").on(columns._order),
    index("pages_blocks_features_parent_id_idx").on(columns._parentID),
    index("pages_blocks_features_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_features_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_features_locales = pgTable(
  "pages_blocks_features_locales",
  {
    headline: varchar("headline"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pages_blocks_features_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_features.id],
      name: "pages_blocks_features_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug").notNull(),
    hero_image: integer("hero_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    hero_ctaPrimary_link: varchar("hero_cta_primary_link"),
    hero_ctaSecondary_link: varchar("hero_cta_secondary_link"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("pages_slug_idx").on(columns.slug),
    index("pages_hero_hero_image_idx").on(columns.hero_image),
    index("pages_meta_meta_image_idx").on(columns.meta_image),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
  ],
);

export const pages_locales = pgTable(
  "pages_locales",
  {
    title: varchar("title").notNull(),
    hero_headline: varchar("hero_headline"),
    hero_subheadline: varchar("hero_subheadline"),
    hero_ctaPrimary_text: varchar("hero_cta_primary_text"),
    hero_ctaSecondary_text: varchar("hero_cta_secondary_text"),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pages_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const cases_social_links = pgTable(
  "cases_social_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    platform: enum_cases_social_links_platform("platform"),
    url: varchar("url"),
  },
  (columns) => [
    index("cases_social_links_order_idx").on(columns._order),
    index("cases_social_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [cases.id],
      name: "cases_social_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const cases = pgTable(
  "cases",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug").notNull(),
    niche: enum_cases_niche("niche").notNull(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    publications: numeric("publications", { mode: "number" }).notNull(),
    views: numeric("views", { mode: "number" }).notNull(),
    revenue: numeric("revenue", { mode: "number" }).notNull(),
    currency: enum_cases_currency("currency").default("RUB"),
    ctr: numeric("ctr", { mode: "number" }),
    conversion: numeric("conversion", { mode: "number" }),
    duration: varchar("duration"),
    published: boolean("published").default(false),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("cases_slug_idx").on(columns.slug),
    index("cases_image_idx").on(columns.image),
    index("cases_updated_at_idx").on(columns.updatedAt),
    index("cases_created_at_idx").on(columns.createdAt),
  ],
);

export const cases_locales = pgTable(
  "cases_locales",
  {
    title: varchar("title").notNull(),
    description: jsonb("description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("cases_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [cases.id],
      name: "cases_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const blog_posts = pgTable(
  "blog_posts",
  {
    id: serial("id").primaryKey(),
    slug: varchar("slug").notNull(),
    category: enum_blog_posts_category("category").notNull(),
    image: integer("image_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    author: integer("author_id").references(() => team.id, {
      onDelete: "set null",
    }),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    published: boolean("published").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("blog_posts_slug_idx").on(columns.slug),
    index("blog_posts_image_idx").on(columns.image),
    index("blog_posts_author_idx").on(columns.author),
    index("blog_posts_updated_at_idx").on(columns.updatedAt),
    index("blog_posts_created_at_idx").on(columns.createdAt),
  ],
);

export const blog_posts_locales = pgTable(
  "blog_posts_locales",
  {
    title: varchar("title").notNull(),
    excerpt: varchar("excerpt").notNull(),
    content: jsonb("content").notNull(),
    meta_title: varchar("meta_title"),
    meta_description: varchar("meta_description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("blog_posts_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [blog_posts.id],
      name: "blog_posts_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pricing_features = pgTable(
  "pricing_features",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    included: boolean("included").default(true),
  },
  (columns) => [
    index("pricing_features_order_idx").on(columns._order),
    index("pricing_features_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pricing.id],
      name: "pricing_features_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pricing_features_locales = pgTable(
  "pricing_features_locales",
  {
    feature: varchar("feature"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pricing_features_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pricing_features.id],
      name: "pricing_features_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pricing = pgTable(
  "pricing",
  {
    id: serial("id").primaryKey(),
    price: numeric("price", { mode: "number" }).notNull(),
    currency: enum_pricing_currency("currency").default("RUB"),
    period: varchar("period").default("месяц"),
    isPopular: boolean("is_popular").default(false),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("pricing_updated_at_idx").on(columns.updatedAt),
    index("pricing_created_at_idx").on(columns.createdAt),
  ],
);

export const pricing_locales = pgTable(
  "pricing_locales",
  {
    name: varchar("name").notNull(),
    description: varchar("description"),
    ctaText: varchar("cta_text").default("Выбрать"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pricing_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pricing.id],
      name: "pricing_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const faq = pgTable(
  "faq",
  {
    id: serial("id").primaryKey(),
    category: enum_faq_category("category").default("general"),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("faq_updated_at_idx").on(columns.updatedAt),
    index("faq_created_at_idx").on(columns.createdAt),
  ],
);

export const faq_locales = pgTable(
  "faq_locales",
  {
    question: varchar("question").notNull(),
    answer: varchar("answer").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("faq_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [faq.id],
      name: "faq_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const team = pgTable(
  "team",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    photo: integer("photo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    telegram: varchar("telegram"),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("team_photo_idx").on(columns.photo),
    index("team_updated_at_idx").on(columns.updatedAt),
    index("team_created_at_idx").on(columns.createdAt),
  ],
);

export const team_locales = pgTable(
  "team_locales",
  {
    role: varchar("role").notNull(),
    bio: jsonb("bio"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("team_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [team.id],
      name: "team_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    pagesID: integer("pages_id"),
    casesID: integer("cases_id"),
    "blog-postsID": integer("blog_posts_id"),
    pricingID: integer("pricing_id"),
    faqID: integer("faq_id"),
    teamID: integer("team_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_cases_id_idx").on(columns.casesID),
    index("payload_locked_documents_rels_blog_posts_id_idx").on(
      columns["blog-postsID"],
    ),
    index("payload_locked_documents_rels_pricing_id_idx").on(columns.pricingID),
    index("payload_locked_documents_rels_faq_id_idx").on(columns.faqID),
    index("payload_locked_documents_rels_team_id_idx").on(columns.teamID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["casesID"]],
      foreignColumns: [cases.id],
      name: "payload_locked_documents_rels_cases_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["blog-postsID"]],
      foreignColumns: [blog_posts.id],
      name: "payload_locked_documents_rels_blog_posts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pricingID"]],
      foreignColumns: [pricing.id],
      name: "payload_locked_documents_rels_pricing_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["faqID"]],
      foreignColumns: [faq.id],
      name: "payload_locked_documents_rels_faq_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["teamID"]],
      foreignColumns: [team.id],
      name: "payload_locked_documents_rels_team_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const header_navigation = pgTable(
  "header_navigation",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    link: varchar("link").notNull(),
  },
  (columns) => [
    index("header_navigation_order_idx").on(columns._order),
    index("header_navigation_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [header.id],
      name: "header_navigation_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const header_navigation_locales = pgTable(
  "header_navigation_locales",
  {
    label: varchar("label").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("header_navigation_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [header_navigation.id],
      name: "header_navigation_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const header = pgTable(
  "header",
  {
    id: serial("id").primaryKey(),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    ctaButton_link: varchar("cta_button_link"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [index("header_logo_idx").on(columns.logo)],
);

export const header_locales = pgTable(
  "header_locales",
  {
    ctaButton_text: varchar("cta_button_text"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("header_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [header.id],
      name: "header_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer_navigation = pgTable(
  "footer_navigation",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    link: varchar("link").notNull(),
  },
  (columns) => [
    index("footer_navigation_order_idx").on(columns._order),
    index("footer_navigation_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer.id],
      name: "footer_navigation_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer_navigation_locales = pgTable(
  "footer_navigation_locales",
  {
    label: varchar("label").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("footer_navigation_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer_navigation.id],
      name: "footer_navigation_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer_social = pgTable(
  "footer_social",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    platform: enum_footer_social_platform("platform"),
    url: varchar("url"),
  },
  (columns) => [
    index("footer_social_order_idx").on(columns._order),
    index("footer_social_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer.id],
      name: "footer_social_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer = pgTable("footer", {
  id: serial("id").primaryKey(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const footer_locales = pgTable(
  "footer_locales",
  {
    description: varchar("description"),
    copyright: varchar("copyright"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("footer_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer.id],
      name: "footer_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const settings = pgTable(
  "settings",
  {
    id: serial("id").primaryKey(),
    siteName: varchar("site_name").default("Content Hunter"),
    defaultMeta_ogImage: integer("default_meta_og_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    contacts_telegram: varchar("contacts_telegram"),
    contacts_telegramBot: varchar("contacts_telegram_bot"),
    contacts_whatsapp: varchar("contacts_whatsapp"),
    contacts_email: varchar("contacts_email"),
    analytics_googleAnalyticsId: varchar("analytics_google_analytics_id"),
    analytics_yandexMetrikaId: varchar("analytics_yandex_metrika_id"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("settings_default_meta_default_meta_og_image_idx").on(
      columns.defaultMeta_ogImage,
    ),
  ],
);

export const settings_locales = pgTable(
  "settings_locales",
  {
    siteDescription: varchar("site_description"),
    defaultMeta_title: varchar("default_meta_title"),
    defaultMeta_description: varchar("default_meta_description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("settings_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [settings.id],
      name: "settings_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_pages_blocks_content_locales = relations(
  pages_blocks_content_locales,
  ({ one }) => ({
    _parentID: one(pages_blocks_content, {
      fields: [pages_blocks_content_locales._parentID],
      references: [pages_blocks_content.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_pages_blocks_content = relations(
  pages_blocks_content,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_content._parentID],
      references: [pages.id],
      relationName: "_blocks_content",
    }),
    _locales: many(pages_blocks_content_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_pages_blocks_cta_locales = relations(
  pages_blocks_cta_locales,
  ({ one }) => ({
    _parentID: one(pages_blocks_cta, {
      fields: [pages_blocks_cta_locales._parentID],
      references: [pages_blocks_cta.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_pages_blocks_cta = relations(
  pages_blocks_cta,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_cta._parentID],
      references: [pages.id],
      relationName: "_blocks_cta",
    }),
    _locales: many(pages_blocks_cta_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_pages_blocks_features_features_locales = relations(
  pages_blocks_features_features_locales,
  ({ one }) => ({
    _parentID: one(pages_blocks_features_features, {
      fields: [pages_blocks_features_features_locales._parentID],
      references: [pages_blocks_features_features.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_pages_blocks_features_features = relations(
  pages_blocks_features_features,
  ({ one, many }) => ({
    _parentID: one(pages_blocks_features, {
      fields: [pages_blocks_features_features._parentID],
      references: [pages_blocks_features.id],
      relationName: "features",
    }),
    _locales: many(pages_blocks_features_features_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_pages_blocks_features_locales = relations(
  pages_blocks_features_locales,
  ({ one }) => ({
    _parentID: one(pages_blocks_features, {
      fields: [pages_blocks_features_locales._parentID],
      references: [pages_blocks_features.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_pages_blocks_features = relations(
  pages_blocks_features,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_features._parentID],
      references: [pages.id],
      relationName: "_blocks_features",
    }),
    _locales: many(pages_blocks_features_locales, {
      relationName: "_locales",
    }),
    features: many(pages_blocks_features_features, {
      relationName: "features",
    }),
  }),
);
export const relations_pages_locales = relations(pages_locales, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_locales._parentID],
    references: [pages.id],
    relationName: "_locales",
  }),
}));
export const relations_pages = relations(pages, ({ one, many }) => ({
  hero_image: one(media, {
    fields: [pages.hero_image],
    references: [media.id],
    relationName: "hero_image",
  }),
  _blocks_content: many(pages_blocks_content, {
    relationName: "_blocks_content",
  }),
  _blocks_cta: many(pages_blocks_cta, {
    relationName: "_blocks_cta",
  }),
  _blocks_features: many(pages_blocks_features, {
    relationName: "_blocks_features",
  }),
  meta_image: one(media, {
    fields: [pages.meta_image],
    references: [media.id],
    relationName: "meta_image",
  }),
  _locales: many(pages_locales, {
    relationName: "_locales",
  }),
}));
export const relations_cases_social_links = relations(
  cases_social_links,
  ({ one }) => ({
    _parentID: one(cases, {
      fields: [cases_social_links._parentID],
      references: [cases.id],
      relationName: "socialLinks",
    }),
  }),
);
export const relations_cases_locales = relations(cases_locales, ({ one }) => ({
  _parentID: one(cases, {
    fields: [cases_locales._parentID],
    references: [cases.id],
    relationName: "_locales",
  }),
}));
export const relations_cases = relations(cases, ({ one, many }) => ({
  image: one(media, {
    fields: [cases.image],
    references: [media.id],
    relationName: "image",
  }),
  socialLinks: many(cases_social_links, {
    relationName: "socialLinks",
  }),
  _locales: many(cases_locales, {
    relationName: "_locales",
  }),
}));
export const relations_blog_posts_locales = relations(
  blog_posts_locales,
  ({ one }) => ({
    _parentID: one(blog_posts, {
      fields: [blog_posts_locales._parentID],
      references: [blog_posts.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_blog_posts = relations(blog_posts, ({ one, many }) => ({
  image: one(media, {
    fields: [blog_posts.image],
    references: [media.id],
    relationName: "image",
  }),
  author: one(team, {
    fields: [blog_posts.author],
    references: [team.id],
    relationName: "author",
  }),
  _locales: many(blog_posts_locales, {
    relationName: "_locales",
  }),
}));
export const relations_pricing_features_locales = relations(
  pricing_features_locales,
  ({ one }) => ({
    _parentID: one(pricing_features, {
      fields: [pricing_features_locales._parentID],
      references: [pricing_features.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_pricing_features = relations(
  pricing_features,
  ({ one, many }) => ({
    _parentID: one(pricing, {
      fields: [pricing_features._parentID],
      references: [pricing.id],
      relationName: "features",
    }),
    _locales: many(pricing_features_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_pricing_locales = relations(
  pricing_locales,
  ({ one }) => ({
    _parentID: one(pricing, {
      fields: [pricing_locales._parentID],
      references: [pricing.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_pricing = relations(pricing, ({ many }) => ({
  features: many(pricing_features, {
    relationName: "features",
  }),
  _locales: many(pricing_locales, {
    relationName: "_locales",
  }),
}));
export const relations_faq_locales = relations(faq_locales, ({ one }) => ({
  _parentID: one(faq, {
    fields: [faq_locales._parentID],
    references: [faq.id],
    relationName: "_locales",
  }),
}));
export const relations_faq = relations(faq, ({ many }) => ({
  _locales: many(faq_locales, {
    relationName: "_locales",
  }),
}));
export const relations_team_locales = relations(team_locales, ({ one }) => ({
  _parentID: one(team, {
    fields: [team_locales._parentID],
    references: [team.id],
    relationName: "_locales",
  }),
}));
export const relations_team = relations(team, ({ one, many }) => ({
  photo: one(media, {
    fields: [team.photo],
    references: [media.id],
    relationName: "photo",
  }),
  _locales: many(team_locales, {
    relationName: "_locales",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    casesID: one(cases, {
      fields: [payload_locked_documents_rels.casesID],
      references: [cases.id],
      relationName: "cases",
    }),
    "blog-postsID": one(blog_posts, {
      fields: [payload_locked_documents_rels["blog-postsID"]],
      references: [blog_posts.id],
      relationName: "blog-posts",
    }),
    pricingID: one(pricing, {
      fields: [payload_locked_documents_rels.pricingID],
      references: [pricing.id],
      relationName: "pricing",
    }),
    faqID: one(faq, {
      fields: [payload_locked_documents_rels.faqID],
      references: [faq.id],
      relationName: "faq",
    }),
    teamID: one(team, {
      fields: [payload_locked_documents_rels.teamID],
      references: [team.id],
      relationName: "team",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_header_navigation_locales = relations(
  header_navigation_locales,
  ({ one }) => ({
    _parentID: one(header_navigation, {
      fields: [header_navigation_locales._parentID],
      references: [header_navigation.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_header_navigation = relations(
  header_navigation,
  ({ one, many }) => ({
    _parentID: one(header, {
      fields: [header_navigation._parentID],
      references: [header.id],
      relationName: "navigation",
    }),
    _locales: many(header_navigation_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_header_locales = relations(
  header_locales,
  ({ one }) => ({
    _parentID: one(header, {
      fields: [header_locales._parentID],
      references: [header.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_header = relations(header, ({ one, many }) => ({
  logo: one(media, {
    fields: [header.logo],
    references: [media.id],
    relationName: "logo",
  }),
  navigation: many(header_navigation, {
    relationName: "navigation",
  }),
  _locales: many(header_locales, {
    relationName: "_locales",
  }),
}));
export const relations_footer_navigation_locales = relations(
  footer_navigation_locales,
  ({ one }) => ({
    _parentID: one(footer_navigation, {
      fields: [footer_navigation_locales._parentID],
      references: [footer_navigation.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_footer_navigation = relations(
  footer_navigation,
  ({ one, many }) => ({
    _parentID: one(footer, {
      fields: [footer_navigation._parentID],
      references: [footer.id],
      relationName: "navigation",
    }),
    _locales: many(footer_navigation_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_footer_social = relations(footer_social, ({ one }) => ({
  _parentID: one(footer, {
    fields: [footer_social._parentID],
    references: [footer.id],
    relationName: "social",
  }),
}));
export const relations_footer_locales = relations(
  footer_locales,
  ({ one }) => ({
    _parentID: one(footer, {
      fields: [footer_locales._parentID],
      references: [footer.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_footer = relations(footer, ({ many }) => ({
  navigation: many(footer_navigation, {
    relationName: "navigation",
  }),
  social: many(footer_social, {
    relationName: "social",
  }),
  _locales: many(footer_locales, {
    relationName: "_locales",
  }),
}));
export const relations_settings_locales = relations(
  settings_locales,
  ({ one }) => ({
    _parentID: one(settings, {
      fields: [settings_locales._parentID],
      references: [settings.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_settings = relations(settings, ({ one, many }) => ({
  defaultMeta_ogImage: one(media, {
    fields: [settings.defaultMeta_ogImage],
    references: [media.id],
    relationName: "defaultMeta_ogImage",
  }),
  _locales: many(settings_locales, {
    relationName: "_locales",
  }),
}));

type DatabaseSchema = {
  enum__locales: typeof enum__locales;
  enum_users_role: typeof enum_users_role;
  enum_cases_social_links_platform: typeof enum_cases_social_links_platform;
  enum_cases_niche: typeof enum_cases_niche;
  enum_cases_currency: typeof enum_cases_currency;
  enum_blog_posts_category: typeof enum_blog_posts_category;
  enum_pricing_currency: typeof enum_pricing_currency;
  enum_faq_category: typeof enum_faq_category;
  enum_footer_social_platform: typeof enum_footer_social_platform;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  pages_blocks_content: typeof pages_blocks_content;
  pages_blocks_content_locales: typeof pages_blocks_content_locales;
  pages_blocks_cta: typeof pages_blocks_cta;
  pages_blocks_cta_locales: typeof pages_blocks_cta_locales;
  pages_blocks_features_features: typeof pages_blocks_features_features;
  pages_blocks_features_features_locales: typeof pages_blocks_features_features_locales;
  pages_blocks_features: typeof pages_blocks_features;
  pages_blocks_features_locales: typeof pages_blocks_features_locales;
  pages: typeof pages;
  pages_locales: typeof pages_locales;
  cases_social_links: typeof cases_social_links;
  cases: typeof cases;
  cases_locales: typeof cases_locales;
  blog_posts: typeof blog_posts;
  blog_posts_locales: typeof blog_posts_locales;
  pricing_features: typeof pricing_features;
  pricing_features_locales: typeof pricing_features_locales;
  pricing: typeof pricing;
  pricing_locales: typeof pricing_locales;
  faq: typeof faq;
  faq_locales: typeof faq_locales;
  team: typeof team;
  team_locales: typeof team_locales;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  header_navigation: typeof header_navigation;
  header_navigation_locales: typeof header_navigation_locales;
  header: typeof header;
  header_locales: typeof header_locales;
  footer_navigation: typeof footer_navigation;
  footer_navigation_locales: typeof footer_navigation_locales;
  footer_social: typeof footer_social;
  footer: typeof footer;
  footer_locales: typeof footer_locales;
  settings: typeof settings;
  settings_locales: typeof settings_locales;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_pages_blocks_content_locales: typeof relations_pages_blocks_content_locales;
  relations_pages_blocks_content: typeof relations_pages_blocks_content;
  relations_pages_blocks_cta_locales: typeof relations_pages_blocks_cta_locales;
  relations_pages_blocks_cta: typeof relations_pages_blocks_cta;
  relations_pages_blocks_features_features_locales: typeof relations_pages_blocks_features_features_locales;
  relations_pages_blocks_features_features: typeof relations_pages_blocks_features_features;
  relations_pages_blocks_features_locales: typeof relations_pages_blocks_features_locales;
  relations_pages_blocks_features: typeof relations_pages_blocks_features;
  relations_pages_locales: typeof relations_pages_locales;
  relations_pages: typeof relations_pages;
  relations_cases_social_links: typeof relations_cases_social_links;
  relations_cases_locales: typeof relations_cases_locales;
  relations_cases: typeof relations_cases;
  relations_blog_posts_locales: typeof relations_blog_posts_locales;
  relations_blog_posts: typeof relations_blog_posts;
  relations_pricing_features_locales: typeof relations_pricing_features_locales;
  relations_pricing_features: typeof relations_pricing_features;
  relations_pricing_locales: typeof relations_pricing_locales;
  relations_pricing: typeof relations_pricing;
  relations_faq_locales: typeof relations_faq_locales;
  relations_faq: typeof relations_faq;
  relations_team_locales: typeof relations_team_locales;
  relations_team: typeof relations_team;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_header_navigation_locales: typeof relations_header_navigation_locales;
  relations_header_navigation: typeof relations_header_navigation;
  relations_header_locales: typeof relations_header_locales;
  relations_header: typeof relations_header;
  relations_footer_navigation_locales: typeof relations_footer_navigation_locales;
  relations_footer_navigation: typeof relations_footer_navigation;
  relations_footer_social: typeof relations_footer_social;
  relations_footer_locales: typeof relations_footer_locales;
  relations_footer: typeof relations_footer;
  relations_settings_locales: typeof relations_settings_locales;
  relations_settings: typeof relations_settings;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
