/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    cases: Case;
    'blog-posts': BlogPost;
    pricing: Pricing;
    faq: Faq;
    team: Team;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    cases: CasesSelect<false> | CasesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en') | ('ru' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
    settings: Setting;
    'home-page': HomePage;
    'services-page': ServicesPage;
    'about-page': AboutPage;
    'pricing-page': PricingPage;
    'faq-page': FaqPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'pricing-page': PricingPageSelect<false> | PricingPageSelect<true>;
    'faq-page': FaqPageSelect<false> | FaqPageSelect<true>;
  };
  locale: 'ru' | 'en';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
    image?: (number | null) | Media;
    ctaPrimary?: {
      text?: string | null;
      link?: string | null;
    };
    ctaSecondary?: {
      text?: string | null;
      link?: string | null;
    };
  };
  blocks?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            headline?: string | null;
            text?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            headline?: string | null;
            features?:
              | {
                  title?: string | null;
                  description?: string | null;
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'features';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases".
 */
export interface Case {
  id: number;
  title: string;
  slug: string;
  niche: 'ecommerce' | 'edu' | 'expert' | 'horeca' | 'beauty' | 'travel' | 'realestate' | 'digital' | 'other';
  image?: (number | null) | Media;
  publications: number;
  views: number;
  revenue: number;
  currency?: ('RUB' | 'USD' | 'EUR') | null;
  ctr?: number | null;
  conversion?: number | null;
  duration?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  socialLinks?:
    | {
        platform?: ('instagram' | 'tiktok' | 'youtube' | 'vk') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * В сайдбаре: «Получить консультацию»
   */
  ctaText?: string | null;
  /**
   * Например: /contact
   */
  ctaLink?: string | null;
  published?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  category: 'cases' | 'analysis' | 'process' | 'myths' | 'news' | 'guides';
  excerpt: string;
  image?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | Team;
  publishedAt?: string | null;
  /**
   * В сайдбаре: «Получить консультацию»
   */
  ctaText?: string | null;
  /**
   * Например: /contact
   */
  ctaLink?: string | null;
  published?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  telegram?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  name: string;
  price: number;
  currency?: ('RUB' | 'USD') | null;
  period?: string | null;
  description?: string | null;
  features?:
    | {
        feature?: string | null;
        included?: boolean | null;
        id?: string | null;
      }[]
    | null;
  isPopular?: boolean | null;
  ctaText?: string | null;
  /**
   * Например: /contact
   */
  ctaLink?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface PricingPro {
  id: number;
  name: string;
  price: number;
  currency?: ('RUB' | 'USD' | 'EUR') | null;
  period?: string | null;
  description?: string | null;
  features?: {
    feature?: string | null;
    included?: boolean | null;
    id?: string | null;
  }[] | null;
  isPopular?: boolean | null;
  ctaText?: string | null;
  ctaLink?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: ('general' | 'services' | 'pricing' | 'process' | 'results' | 'technical' | 'niches') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'cases';
        value: number | Case;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'pricing';
        value: number | Pricing;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        image?: T;
        ctaPrimary?:
          | T
          | {
              text?: T;
              link?: T;
            };
        ctaSecondary?:
          | T
          | {
              text?: T;
              link?: T;
            };
      };
  blocks?:
    | T
    | {
        content?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              headline?: T;
              text?: T;
              buttonText?: T;
              buttonLink?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              headline?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cases_select".
 */
export interface CasesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  niche?: T;
  image?: T;
  publications?: T;
  views?: T;
  revenue?: T;
  currency?: T;
  ctr?: T;
  conversion?: T;
  duration?: T;
  description?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  ctaText?: T;
  ctaLink?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  image?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  ctaText?: T;
  ctaLink?: T;
  published?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  name?: T;
  price?: T;
  currency?: T;
  period?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        included?: T;
        id?: T;
      };
  isPopular?: T;
  ctaText?: T;
  ctaLink?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  telegram?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navigation?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    text?: string | null;
    link?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  description?: string | null;
  navigation?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ссылки на документы в блоке «Материалы»
   */
  materials?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  social?:
    | {
        platform?: ('telegram' | 'instagram' | 'youtube' | 'tiktok' | 'whatsapp') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  siteDescription?: string | null;
  defaultMeta?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  contacts?: {
    telegram?: string | null;
    telegramBot?: string | null;
    whatsapp?: string | null;
    email?: string | null;
  };
  analytics?: {
    /**
     * Оставьте пустым, если не используется
     */
    googleAnalyticsId?: string | null;
    /**
     * Только число, например 12345678
     */
    yandexMetrikaId?: string | null;
    /**
     * HTML-код (скрипты, мета-теги). Вставляется перед </head>. Например: <script>...</script>
     */
    customHeadScripts?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
    primaryButtonText?: string | null;
    /**
     * Например: /contact
     */
    primaryButtonLink?: string | null;
    secondaryButtonText?: string | null;
    /**
     * Например: /cases
     */
    secondaryButtonLink?: string | null;
    stats?:
      | {
          value?: string | null;
          suffix?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    cycleWords?:
      | {
          word?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  problem?: {
    title?: string | null;
    text?: string | null;
    items?:
      | {
          icon?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  solution?: {
    title?: string | null;
    titleHighlight?: string | null;
    formula?: string | null;
    text?: string | null;
    checklist?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
    formulaStats?:
      | {
          value?: number | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  stats?: {
    items?:
      | {
          value?: number | null;
          suffix?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  howItWorks?: {
    title?: string | null;
    subtitle?: string | null;
    steps?:
      | {
          icon?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  videoExamples?: {
    title?: string | null;
    subtitle?: string | null;
    items?:
      | {
          client?: string | null;
          format?: string | null;
          instagramIds?:
            | {
                id?: string | null;
                label?: string | null;
              }[]
            | null;
          youtubeIds?:
            | {
                id?: string | null;
                label?: string | null;
              }[]
            | null;
          /**
           * Работает в РФ, в отличие от YouTube/Instagram
           */
          vimeoIds?:
            | {
                id?: string | null;
                label?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  niches?: {
    title?: string | null;
    subtitle?: string | null;
    items?:
      | {
          icon?: string | null;
          name?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  comparison?: {
    title?: string | null;
    subtitle?: string | null;
    competitors?:
      | {
          title?: string | null;
          description?: string | null;
          cons?:
            | {
                item?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    ourAdvantages?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    headline?: string | null;
    headlineHighlight?: string | null;
    text?: string | null;
    guarantees?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
    primaryButtonText?: string | null;
    /**
     * Например: /contact
     */
    primaryButtonLink?: string | null;
    /**
     * Например: Написать в Telegram
     */
    secondaryButtonText?: string | null;
    /**
     * Ссылка Telegram, например: https://t.me/...
     */
    telegramLink?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  hero?: {
    headline?: string | null;
    headlineHighlight?: string | null;
    subheadline?: string | null;
    primaryButtonText?: string | null;
    /**
     * Например: /contact
     */
    primaryButtonLink?: string | null;
    secondaryButtonText?: string | null;
    /**
     * Например: /cases
     */
    secondaryButtonLink?: string | null;
  };
  whatIs?: {
    title?: string | null;
    paragraphs?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    benefits?:
      | {
          item?: string | null;
          id?: string | null;
        }[]
      | null;
    formulaValues?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  formats?: {
    title?: string | null;
    subtitle?: string | null;
    items?:
      | {
          icon?: string | null;
          title?: string | null;
          description?: string | null;
          platforms?:
            | {
                name?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  stages?: {
    title?: string | null;
    subtitle?: string | null;
    items?:
      | {
          number?: string | null;
          title?: string | null;
          description?: string | null;
          duration?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  scaling?: {
    title?: string | null;
    subtitle?: string | null;
    items?:
      | {
          icon?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    headline?: string | null;
    headlineHighlight?: string | null;
    text?: string | null;
    primaryButtonText?: string | null;
    /**
     * Например: /contact
     */
    primaryButtonLink?: string | null;
    secondaryButtonText?: string | null;
    /**
     * Например: /pricing
     */
    secondaryButtonLink?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
  };
  stats?: {
    items?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  story?: {
    title?: string | null;
    paragraphs?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  values?: {
    title?: string | null;
    subtitle?: string | null;
    items?:
      | {
          icon?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  geography?: {
    title?: string | null;
    text?: string | null;
    regions?:
      | {
          name?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  company?: {
    title?: string | null;
    companyName?: string | null;
    brand?: string | null;
    founder?: string | null;
    year?: string | null;
  };
  cta?: {
    headline?: string | null;
    text?: string | null;
    buttonText?: string | null;
    /**
     * Например: /contact
     */
    buttonLink?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-page".
 */
export interface PricingPage {
  id: number;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
  };
  cta?: {
    headline?: string | null;
    text?: string | null;
    buttonText?: string | null;
    /**
     * Например: /contact
     */
    buttonLink?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page".
 */
export interface FaqPage {
  id: number;
  hero?: {
    headline?: string | null;
    headlineHighlight?: string | null;
    subheadline?: string | null;
    buttonText?: string | null;
    /**
     * Например: #questions или /contact
     */
    buttonLink?: string | null;
  };
  cta?: {
    headline?: string | null;
    text?: string | null;
    buttonText?: string | null;
    /**
     * Например: /contact
     */
    buttonLink?: string | null;
  };
  categories?:
    | {
        id?: string | null;
        label?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navigation?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        text?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  navigation?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  materials?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  defaultMeta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  contacts?:
    | T
    | {
        telegram?: T;
        telegramBot?: T;
        whatsapp?: T;
        email?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
        yandexMetrikaId?: T;
        customHeadScripts?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
        stats?:
          | T
          | {
              value?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
        cycleWords?:
          | T
          | {
              word?: T;
              id?: T;
            };
      };
  problem?:
    | T
    | {
        title?: T;
        text?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  solution?:
    | T
    | {
        title?: T;
        titleHighlight?: T;
        formula?: T;
        text?: T;
        checklist?:
          | T
          | {
              item?: T;
              id?: T;
            };
        formulaStats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        items?:
          | T
          | {
              value?: T;
              suffix?: T;
              label?: T;
              id?: T;
            };
      };
  howItWorks?:
    | T
    | {
        title?: T;
        subtitle?: T;
        steps?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  videoExamples?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              client?: T;
              format?: T;
              instagramIds?:
                | T
                | {
                    id?: T;
                    label?: T;
                  };
              youtubeIds?:
                | T
                | {
                    id?: T;
                    label?: T;
                  };
              vimeoIds?:
                | T
                | {
                    id?: T;
                    label?: T;
                  };
              id?: T;
            };
      };
  niches?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              icon?: T;
              name?: T;
              description?: T;
              id?: T;
            };
      };
  comparison?:
    | T
    | {
        title?: T;
        subtitle?: T;
        competitors?:
          | T
          | {
              title?: T;
              description?: T;
              cons?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              id?: T;
            };
        ourAdvantages?:
          | T
          | {
              item?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        headline?: T;
        headlineHighlight?: T;
        text?: T;
        guarantees?:
          | T
          | {
              item?: T;
              id?: T;
            };
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        telegramLink?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        headlineHighlight?: T;
        subheadline?: T;
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
      };
  whatIs?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        benefits?:
          | T
          | {
              item?: T;
              id?: T;
            };
        formulaValues?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  formats?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              platforms?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  stages?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              duration?: T;
              id?: T;
            };
      };
  scaling?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        headline?: T;
        headlineHighlight?: T;
        text?: T;
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
      };
  stats?:
    | T
    | {
        items?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  story?:
    | T
    | {
        title?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  values?:
    | T
    | {
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  geography?:
    | T
    | {
        title?: T;
        text?: T;
        regions?:
          | T
          | {
              name?: T;
              id?: T;
            };
      };
  company?:
    | T
    | {
        title?: T;
        companyName?: T;
        brand?: T;
        founder?: T;
        year?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        text?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-page_select".
 */
export interface PricingPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        text?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-page_select".
 */
export interface FaqPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        headlineHighlight?: T;
        subheadline?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        text?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  categories?:
    | T
    | {
        id?: T;
        label?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
